### ISSUE TITLE
Retry after https error

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Naoko#129]
When there is no internet, the bot crashes and then waits for the files to be changed

**Comment by otiskujawa** [comment]
![image](https://user-images.githubusercontent.com/49094075/152877037-fec6fb55-eba3-4c08-8f1a-afc2ba86398c.png)

**Comment by LeVonara9** [comment]
It's simply because when disconnected, you cannot make HTTP request and connect to the discord API.

## To fix here is the steps.

### Linux [Source: Stack overflow](https://stackoverflow.com/questions/37486631/nodemon-app-crashed-waiting-for-file-changes-before-starting)
- `pkill -f node`
- Restart nodemon

### Windows
- `CTRL + c` on your terminal. Doesn't matter if it's powershell or command prompt
- Restart nodemon

Tested with windows 10 and node version 16.13.2

**Comment by LeVonara9** [comment]
I don't think that's possible because the bot doesn't really disconnects from internet. If the bot is active locally meaning you started it from your terminal. It needs your internet connection to actually work.

### Here is what I got.
- My pc is connected to wifi: 5 tries and works totally fine.
- My pc is not connected to wifi: 5 tries and the application still crashes.

Thus it means if your machine still doesn't have internet and the app crashes and the HTTP error occur, it cannot (in my theory and opinion) technically tag a server or send any message.
If you meant to restart automatically after it disconnects, it might crash again and again hence making a bad loop.
